import { nodeRegistry } from '../node-registry.js';
import { KafkaInputNode } from './kafka-input.node.js';
import { LogNode } from './log.node.js';
import { ScriptFilterNode } from './script-filter.node.js';
import { ThresholdFilterNode } from './threshold-filter.node.js';
import { MessageTypeSwitchNode } from './message-type-switch.node.js';
import { CheckRelationNode } from './check-relation.node.js';
import { GeofencingNode } from './geofencing.node.js';
import { OriginatorTypeFilterNode } from './originator-type-filter.node.js';
import { SwitchNode } from './switch.node.js';
import { ScriptTransformNode } from './script-transform.node.js';
import { MathNode } from './math.node.js';
import { FormulaNode } from './formula.node.js';
import { CreateAlarmNode } from './create-alarm.node.js';
import { KafkaPublishNode } from './kafka-publish.node.js';
import { FetchAssetAttributesNode } from './fetch-asset-attributes.node.js';
import { FetchAssetTelemetryNode } from './fetch-asset-telemetry.node.js';
import { SaveTimeseriesNode } from './save-timeseries.node.js';
import { UpdateDittoFeatureNode } from './update-ditto-feature.node.js';
import { RuleChainNode } from './rule-chain.node.js';
import { FetchAssetMetadataNode } from './fetch-asset-metadata.node.js';
import { FetchRelatedAssetsNode } from './fetch-related-assets.node.js';
import { CalculateDeltaNode } from './calculate-delta.node.js';
import { LookupTableNode } from './lookup-table.node.js';
import { OriginatorFieldsNode } from './originator-fields.node.js';
import { RelatedAttributesNode } from './related-attributes.node.js';
import { AggregateNode } from './aggregate.node.js';
import { UnitConversionNode } from './unit-conversion.node.js';
import { JsonPathNode } from './json-path.node.js';
import { RenameKeysNode } from './rename-keys.node.js';
import { ChangeOriginatorNode } from './change-originator.node.js';
import { UpdateAssetAttributesNode } from './update-asset-attributes.node.js';
import { SendEmailNode } from './send-email.node.js';
import { RestApiCallNode } from './rest-api-call.node.js';
import { ClearAlarmNode } from './clear-alarm.node.js';
import { AcknowledgeAlarmNode } from './acknowledge-alarm.node.js';
import { DelayNode } from './delay.node.js';
import { MqttPublishNode } from './mqtt-publish.node.js';
import { SlackNode } from './slack.node.js';
import { MergeNode } from './merge.node.js';
import { SplitNode } from './split.node.js';
import { CheckFieldsPresenceNode } from './check-fields-presence.node.js';
import { EntityTypeFilterNode } from './entity-type-filter.node.js';
import { EntityTypeSwitchNode } from './entity-type-switch.node.js';
import { AlarmStatusFilterNode } from './alarm-status-filter.node.js';
import { OriginatorAttributesNode } from './originator-attributes.node.js';
import { OriginatorTelemetryNode } from './originator-telemetry.node.js';
import { SaveAttributesNode } from './save-attributes.node.js';
import { DeleteAttributesNode } from './delete-attributes.node.js';
import { InputNode } from './input.node.js';
import { OutputNode } from './output.node.js';
import { AcknowledgeNode } from './acknowledge.node.js';
import { CheckpointNode } from './checkpoint.node.js';
import { CreateRelationNode } from './create-relation.node.js';
import { DeleteRelationNode } from './delete-relation.node.js';
import { GeneratorNode } from './generator.node.js';
import { SendNotificationNode } from './send-notification.node.js';
import { RpcCallNode } from './rpc-call.node.js';
import { TenantAttributesNode } from './tenant-attributes.node.js';
import { DeviceAttributesNode } from './device-attributes.node.js';
import { AssignToCustomerNode } from './assign-to-customer.node.js';
import { UnassignFromCustomerNode } from './unassign-from-customer.node.js';
import { MessageCountNode } from './message-count.node.js';
import { SetStatusNode } from './set-status.node.js';
import { DataSourceInputNode } from './data-source-input.node.js';
import { ResolveBindingNode } from './resolve-binding.node.js';
import { ApplyMappingNode } from './apply-mapping.node.js';
import { RouteToComponentsNode } from './route-to-components.node.js';
import { SaveToDigitalTwinNode } from './save-to-digital-twin.node.js';

export function registerDefaultNodes() {
  // Input nodes
  nodeRegistry.register('kafka_input', KafkaInputNode as any);
  nodeRegistry.register('data_source_input', DataSourceInputNode as any);
  
  // Filter nodes
  nodeRegistry.register('script_filter', ScriptFilterNode as any);
  nodeRegistry.register('threshold_filter', ThresholdFilterNode as any);
  nodeRegistry.register('message_type_switch', MessageTypeSwitchNode as any);
  nodeRegistry.register('check_relation', CheckRelationNode as any);
  nodeRegistry.register('geofencing', GeofencingNode as any);
  nodeRegistry.register('originator_type_filter', OriginatorTypeFilterNode as any);
  nodeRegistry.register('switch', SwitchNode as any);
  nodeRegistry.register('check_fields_presence', CheckFieldsPresenceNode as any);
  nodeRegistry.register('entity_type_filter', EntityTypeFilterNode as any);
  nodeRegistry.register('entity_type_switch', EntityTypeSwitchNode as any);
  nodeRegistry.register('alarm_status_filter', AlarmStatusFilterNode as any);
  
  // Transform nodes
  nodeRegistry.register('script_transform', ScriptTransformNode as any);
  nodeRegistry.register('math', MathNode as any);
  nodeRegistry.register('formula', FormulaNode as any);
  nodeRegistry.register('aggregate', AggregateNode as any);
  nodeRegistry.register('unit_conversion', UnitConversionNode as any);
  nodeRegistry.register('json_path', JsonPathNode as any);
  nodeRegistry.register('rename_keys', RenameKeysNode as any);
  nodeRegistry.register('change_originator', ChangeOriginatorNode as any);
  
  // Enrichment nodes
  nodeRegistry.register('fetch_asset_attributes', FetchAssetAttributesNode as any);
  nodeRegistry.register('fetch_asset_telemetry', FetchAssetTelemetryNode as any);
  nodeRegistry.register('fetch_asset_metadata', FetchAssetMetadataNode as any);
  nodeRegistry.register('fetch_related_assets', FetchRelatedAssetsNode as any);
  nodeRegistry.register('calculate_delta', CalculateDeltaNode as any);
  nodeRegistry.register('lookup_table', LookupTableNode as any);
  nodeRegistry.register('originator_fields', OriginatorFieldsNode as any);
  nodeRegistry.register('related_attributes', RelatedAttributesNode as any);
  nodeRegistry.register('originator_attributes', OriginatorAttributesNode as any);
  nodeRegistry.register('originator_telemetry', OriginatorTelemetryNode as any);
  nodeRegistry.register('tenant_attributes', TenantAttributesNode as any);
  nodeRegistry.register('device_attributes', DeviceAttributesNode as any);
  nodeRegistry.register('resolve_binding', ResolveBindingNode as any);
  
  // Transform nodes (Data Source Mapping)
  nodeRegistry.register('apply_mapping', ApplyMappingNode as any);
  nodeRegistry.register('route_to_components', RouteToComponentsNode as any);
  
  // Action nodes
  nodeRegistry.register('log', LogNode as any);
  nodeRegistry.register('create_alarm', CreateAlarmNode as any);
  nodeRegistry.register('kafka_publish', KafkaPublishNode as any);
  nodeRegistry.register('save_timeseries', SaveTimeseriesNode as any);
  nodeRegistry.register('update_ditto_feature', UpdateDittoFeatureNode as any);
  nodeRegistry.register('save_to_digital_twin', SaveToDigitalTwinNode as any);
  nodeRegistry.register('update_asset_attributes', UpdateAssetAttributesNode as any);
  nodeRegistry.register('send_email', SendEmailNode as any);
  nodeRegistry.register('rest_api_call', RestApiCallNode as any);
  nodeRegistry.register('clear_alarm', ClearAlarmNode as any);
  nodeRegistry.register('acknowledge_alarm', AcknowledgeAlarmNode as any);
  nodeRegistry.register('delay', DelayNode as any);
  nodeRegistry.register('save_attributes', SaveAttributesNode as any);
  nodeRegistry.register('delete_attributes', DeleteAttributesNode as any);
  nodeRegistry.register('create_relation', CreateRelationNode as any);
  nodeRegistry.register('delete_relation', DeleteRelationNode as any);
  nodeRegistry.register('generator', GeneratorNode as any);
  nodeRegistry.register('rpc_call', RpcCallNode as any);
  nodeRegistry.register('assign_to_customer', AssignToCustomerNode as any);
  nodeRegistry.register('unassign_from_customer', UnassignFromCustomerNode as any);
  nodeRegistry.register('message_count', MessageCountNode as any);
  nodeRegistry.register('set_status', SetStatusNode as any);
  
  // External nodes
  nodeRegistry.register('mqtt_publish', MqttPublishNode as any);
  nodeRegistry.register('slack', SlackNode as any);
  nodeRegistry.register('send_notification', SendNotificationNode as any);
  
  // Flow nodes
  nodeRegistry.register('rule_chain', RuleChainNode as any);
  nodeRegistry.register('merge', MergeNode as any);
  nodeRegistry.register('split', SplitNode as any);
  nodeRegistry.register('input', InputNode as any);
  nodeRegistry.register('output', OutputNode as any);
  nodeRegistry.register('acknowledge', AcknowledgeNode as any);
  nodeRegistry.register('checkpoint', CheckpointNode as any);
}

export * from './kafka-input.node.js';
export * from './log.node.js';
export * from './script-filter.node.js';
export * from './threshold-filter.node.js';
export * from './message-type-switch.node.js';
export * from './check-relation.node.js';
export * from './geofencing.node.js';
export * from './originator-type-filter.node.js';
export * from './switch.node.js';
export * from './script-transform.node.js';
export * from './math.node.js';
export * from './formula.node.js';
export * from './create-alarm.node.js';
export * from './kafka-publish.node.js';
export * from './fetch-asset-attributes.node.js';
export * from './fetch-asset-telemetry.node.js';
export * from './save-timeseries.node.js';
export * from './update-ditto-feature.node.js';
export * from './rule-chain.node.js';
export * from './fetch-asset-metadata.node.js';
export * from './fetch-related-assets.node.js';
export * from './calculate-delta.node.js';
export * from './lookup-table.node.js';
export * from './originator-fields.node.js';
export * from './related-attributes.node.js';
export * from './aggregate.node.js';
export * from './unit-conversion.node.js';
export * from './json-path.node.js';
export * from './rename-keys.node.js';
export * from './change-originator.node.js';
export * from './update-asset-attributes.node.js';
export * from './send-email.node.js';
export * from './rest-api-call.node.js';
export * from './clear-alarm.node.js';
export * from './acknowledge-alarm.node.js';
export * from './delay.node.js';
export * from './mqtt-publish.node.js';
export * from './slack.node.js';
export * from './merge.node.js';
export * from './split.node.js';
export * from './check-fields-presence.node.js';
export * from './entity-type-filter.node.js';
export * from './entity-type-switch.node.js';
export * from './alarm-status-filter.node.js';
export * from './originator-attributes.node.js';
export * from './originator-telemetry.node.js';
export * from './save-attributes.node.js';
export * from './delete-attributes.node.js';
export * from './input.node.js';
export * from './output.node.js';
export * from './acknowledge.node.js';
export * from './checkpoint.node.js';
export * from './create-relation.node.js';
export * from './delete-relation.node.js';
export * from './generator.node.js';
export * from './send-notification.node.js';
export * from './rpc-call.node.js';
export * from './tenant-attributes.node.js';
export * from './device-attributes.node.js';
export * from './assign-to-customer.node.js';
export * from './unassign-from-customer.node.js';
export * from './message-count.node.js';
export * from './set-status.node.js';
export * from './data-source-input.node.js';
export * from './resolve-binding.node.js';
export * from './apply-mapping.node.js';
export * from './route-to-components.node.js';
export * from './save-to-digital-twin.node.js';
